networks:
  kafka-net:
    driver: bridge
services:
  kafka1:
    image: apache/kafka:4.1.1
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker, controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'Fmdt3WHo34rGxx-TH2n0L2'
    volumes:
      - ./kafka1/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka2:
    image: apache/kafka:4.1.1
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9094:9092"
      - "9095:9093"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: 'broker, controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka2:9092,CONTROLLER://kafka2:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'Fmdt3WHo34rGxx-TH2n0L2'
    volumes:
      - ./kafka2/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka3:
    image: apache/kafka:4.1.1
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9096:9092"
      - "9097:9093"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: 'broker, controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka3:9092,CONTROLLER://kafka3:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'Fmdt3WHo34rGxx-TH2n0L2'
    volumes:
      - ./kafka3/data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net

  kafka-train-topic-init:
    image: apache/kafka:4.1.1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net
    command: > 
      sh -c "sleep 5 &&
      /opt/kafka/bin/kafka-topics.sh --create --topic tweet-train --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --replication-factor 3 --partitions 2"
    
  kafka-test-topic-init:
    image: apache/kafka:4.1.1
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - kafka-net
    command: > 
      sh -c "sleep 5 &&
      /opt/kafka/bin/kafka-topics.sh --create --topic tweet-test --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --replication-factor 3 --partitions 2"

  kafka-topic-check:
    image: apache/kafka:4.1.1
    depends_on:
      kafka-train-topic-init:
        condition: service_completed_successfully
      kafka-test-topic-init:
        condition: service_completed_successfully
    networks:
      - kafka-net
    command: > 
      sh -c "/opt/kafka/bin/kafka-topics.sh --describe --topic tweet-train --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 &&
             /opt/kafka/bin/kafka-topics.sh --describe --topic tweet-test --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092"
  
  train-data-producer:
    image: data-producer
    hostname: train-data-producer
    container_name: train-data-producer
    depends_on:
      kafka-train-topic-init:
        condition: service_completed_successfully
    volumes:
      - ./shared:/pipeline/data
    networks:
    - kafka-net
    command: /pipeline/scripts/producer_train.py 3 

  spark-model-builder:
    image: spark-processor
    depends_on:
      train-data-producer:
        condition: service_completed_successfully
    volumes:
      - ./shared:/pipeline/data
    networks:
      - kafka-net
    command: >
      /opt/spark/bin/spark-submit
      --driver-memory 24g 
      --executor-memory 16g 
      --conf "spark.jars.ivy=/tmp/.ivy2"
      --packages "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.4,com.johnsnowlabs.nlp:spark-nlp_2.12:6.3.0"
      --files "log4j.properties" 
      --conf "spark.driver.extraJavaOptions=-Dlog4j.configuration=file:log4j.properties" 
      --conf "spark.executor.extraJavaOptions=-Dlog4j.configuration=file:log4j.properties" 
      --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" 
      --conf "spark.kryoserializer.buffer.max=2000M" 
      /pipeline/scripts/model_train.py 3

  spark-predictor:
    image: spark-processor
    depends_on:
      spark-model-builder:
        condition: service_completed_successfully
    volumes:
      - ./shared:/pipeline/data
    networks:
      - kafka-net
    command: >
      /opt/spark/bin/spark-submit
      --driver-memory 24g 
      --executor-memory 16g 
      --conf "spark.jars.ivy=/tmp/.ivy2"
      --packages "org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.4,com.johnsnowlabs.nlp:spark-nlp_2.12:6.3.0"
      --files "log4j.properties" 
      --conf "spark.driver.extraJavaOptions=-Dlog4j.configuration=file:log4j.properties" 
      --conf "spark.executor.extraJavaOptions=-Dlog4j.configuration=file:log4j.properties" 
      --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" 
      --conf "spark.kryoserializer.buffer.max=2000M" 
      /pipeline/scripts/model_test.py 3

  test-data-producer:
    image: data-producer
    hostname: test-data-producer
    container_name: test-data-producer
    depends_on:
      spark-model-builder:
        condition: service_completed_successfully
    volumes:
      - ./shared:/pipeline/data
    networks:
    - kafka-net
    command: >
      sh -c "sleep 25 &&
      /pipeline/scripts/producer_test.py 3"

